# Telecommunication Industry Data Analysis

## Import the packages

In [2]:

import pandas as pd
import numpy as np
import warnings
import matplotlib.pyplot as plt
import sys, os
 
sys.path.append(os.path.abspath(os.path.join('../scripts')))
from load_data import LoadData
sys.path.append(os.path.abspath(os.path.join('../tests')))
import test_load_data

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\user\anaconda3\envs\envmysql\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\user\anaconda3\envs\envmysql\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

## Loading the data into a dataframe

In [3]:
telco_pd = pd.read_excel('../data/Week1_challenge_data_source.xlsx',engine='openpyxl')
telco_pd.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

## Data Cleaning

In [4]:
warnings.filterwarnings('ignore')
pd.set_option('display.max_column', None)
telco_pd.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [5]:
telco_df_dropped.head(5000)

NameError: name 'telco_df_dropped' is not defined

In [13]:
telco_df=telco_pd
telco_df.columns.tolist()

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

### Handling Missing Values

In [14]:
# how many missing values exist or better still what is the % of missing values in the dataset?
def percent_missing(df):

    # Calculate total number of cells in dataframe
    totalCells = np.product(df.shape)

    # Count number of missing values per column
    missingCount = df.isnull().sum()

    # Calculate total number of missing values
    totalMissing = missingCount.sum()

    # Calculate percentage of missing values
    print("The Telecommunication Industry dataset contains", round(((totalMissing/totalCells) * 100), 2), "%", "missing values.")

percent_missing(telco_df)

The Telecommunication Industry dataset contains 12.49 % missing values.

In [15]:
# Now which column(s) has missing values
telco_df.isna().sum()

Bearer Id                                        0
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [16]:
#calculate the percentage of missing values in each column
telco_df.isna().mean().round(4) * 100

Bearer Id                                    0.00
Start                                        0.00
Start ms                                     0.00
End                                          0.00
End ms                                       0.00
Dur. (ms)                                    0.00
IMSI                                         0.38
MSISDN/Number                                0.71
IMEI                                         0.38
Last Location Name                           0.77
Avg RTT DL (ms)                             18.55
Avg RTT UL (ms)                             18.54
Avg Bearer TP DL (kbps)                      0.00
Avg Bearer TP UL (kbps)                      0.00
TCP DL Retrans. Vol (Bytes)                 58.76
TCP UL Retrans. Vol (Bytes)                 64.43
DL TP < 50 Kbps (%)                          0.50
50 Kbps < DL TP < 250 Kbps (%)               0.50
250 Kbps < DL TP < 1 Mbps (%)                0.50
DL TP > 1 Mbps (%)                           0.50
UL TP < 10 Kbps (%)                          0.53
10 Kbps < UL TP < 50 Kbps (%)                0.53
50 Kbps < UL TP < 300 Kbps (%)               0.53
UL TP > 300 Kbps (%)                         0.53
HTTP DL (Bytes)                             54.32
HTTP UL (Bytes)                             54.54
Activity Duration DL (ms)                    0.00
Activity Duration UL (ms)                    0.00
Dur. (ms).1                                  0.00
Handset Manufacturer                         0.38
Handset Type                                 0.38
Nb of sec with 125000B < Vol DL             65.02
Nb of sec with 1250B < Vol UL < 6250B       61.93
Nb of sec with 31250B < Vol DL < 125000B    62.39
Nb of sec with 37500B < Vol UL              86.84
Nb of sec with 6250B < Vol DL < 31250B      58.88
Nb of sec with 6250B < Vol UL < 37500B      74.56
Nb of sec with Vol DL < 6250B                0.50
Nb of sec with Vol UL < 1250B                0.53
Social Media DL (Bytes)                      0.00
Social Media UL (Bytes)                      0.00
Google DL (Bytes)                            0.00
Google UL (Bytes)                            0.00
Email DL (Bytes)                             0.00
Email UL (Bytes)                             0.00
Youtube DL (Bytes)                           0.00
Youtube UL (Bytes)                           0.00
Netflix DL (Bytes)                           0.00
Netflix UL (Bytes)                           0.00
Gaming DL (Bytes)                            0.00
Gaming UL (Bytes)                            0.00
Other DL (Bytes)                             0.00
Other UL (Bytes)                             0.00
Total UL (Bytes)                             0.00
Total DL (Bytes)                             0.00
dtype: float64

In [17]:
#get the number of rows in the dataframe before dropping
telco_df.shape

(150001, 55)

In [22]:
#drop rows with missing imei, msisdn, imsi, handset manufacturer and handset type
telco_df_dropped = telco_df.dropna(subset=['IMSI', 'MSISDN/Number', 'IMEI', 'Handset Manufacturer', 'Handset Type', 'Last Location Name'])
telco_df_dropped.shape #show the new shape of the dataframe

(148346, 55)

In [19]:
telco_df_dropped.isna().mean().round(4) * 100

Bearer Id                                    0.00
Start                                        0.00
Start ms                                     0.00
End                                          0.00
End ms                                       0.00
Dur. (ms)                                    0.00
IMSI                                         0.00
MSISDN/Number                                0.00
IMEI                                         0.00
Last Location Name                           0.40
Avg RTT DL (ms)                             18.56
Avg RTT UL (ms)                             18.55
Avg Bearer TP DL (kbps)                      0.00
Avg Bearer TP UL (kbps)                      0.00
TCP DL Retrans. Vol (Bytes)                 58.95
TCP UL Retrans. Vol (Bytes)                 64.59
DL TP < 50 Kbps (%)                          0.48
50 Kbps < DL TP < 250 Kbps (%)               0.48
250 Kbps < DL TP < 1 Mbps (%)                0.48
DL TP > 1 Mbps (%)                           0.48
UL TP < 10 Kbps (%)                          0.51
10 Kbps < UL TP < 50 Kbps (%)                0.51
50 Kbps < UL TP < 300 Kbps (%)               0.51
UL TP > 300 Kbps (%)                         0.51
HTTP DL (Bytes)                             54.50
HTTP UL (Bytes)                             54.73
Activity Duration DL (ms)                    0.00
Activity Duration UL (ms)                    0.00
Dur. (ms).1                                  0.00
Handset Manufacturer                         0.00
Handset Type                                 0.00
Nb of sec with 125000B < Vol DL             65.12
Nb of sec with 1250B < Vol UL < 6250B       62.06
Nb of sec with 31250B < Vol DL < 125000B    62.51
Nb of sec with 37500B < Vol UL              86.84
Nb of sec with 6250B < Vol DL < 31250B      59.03
Nb of sec with 6250B < Vol UL < 37500B      74.60
Nb of sec with Vol DL < 6250B                0.48
Nb of sec with Vol UL < 1250B                0.52
Social Media DL (Bytes)                      0.00
Social Media UL (Bytes)                      0.00
Google DL (Bytes)                            0.00
Google UL (Bytes)                            0.00
Email DL (Bytes)                             0.00
Email UL (Bytes)                             0.00
Youtube DL (Bytes)                           0.00
Youtube UL (Bytes)                           0.00
Netflix DL (Bytes)                           0.00
Netflix UL (Bytes)                           0.00
Gaming DL (Bytes)                            0.00
Gaming UL (Bytes)                            0.00
Other DL (Bytes)                             0.00
Other UL (Bytes)                             0.00
Total UL (Bytes)                             0.00
Total DL (Bytes)                             0.00
dtype: float64

In [21]:
#Functions for filling

def fix_missing_ffill(df, col):
    df[col] = df[col].fillna(method='ffill')
    return df[col]


def fix_missing_bfill(df, col):
    df[col] = df[col].fillna(method='bfill')
    return df[col]

In [23]:
telco_df_dropped.isna().sum()

Bearer Id                                        0
Start                                            0
Start ms                                         0
End                                              0
End ms                                           0
Dur. (ms)                                        0
IMSI                                             0
MSISDN/Number                                    0
IMEI                                             0
Last Location Name                               0
Avg RTT DL (ms)                              27598
Avg RTT UL (ms)                              27578
Avg Bearer TP DL (kbps)                          0
Avg Bearer TP UL (kbps)                          0
TCP DL Retrans. Vol (Bytes)                  87681
TCP UL Retrans. Vol (Bytes)                  96029
DL TP < 50 Kbps (%)                            688
50 Kbps < DL TP < 250 Kbps (%)                 688
250 Kbps < DL TP < 1 Mbps (%)                  688
DL TP > 1 Mbps (%)                             688
UL TP < 10 Kbps (%)                            765
10 Kbps < UL TP < 50 Kbps (%)                  765
50 Kbps < UL TP < 300 Kbps (%)                 765
UL TP > 300 Kbps (%)                           765
HTTP DL (Bytes)                              81057
HTTP UL (Bytes)                              81412
Activity Duration DL (ms)                        0
Activity Duration UL (ms)                        0
Dur. (ms).1                                      0
Handset Manufacturer                             0
Handset Type                                     0
Nb of sec with 125000B < Vol DL              96673
Nb of sec with 1250B < Vol UL < 6250B        92172
Nb of sec with 31250B < Vol DL < 125000B     92878
Nb of sec with 37500B < Vol UL              128800
Nb of sec with 6250B < Vol DL < 31250B       87747
Nb of sec with 6250B < Vol UL < 37500B      110674
Nb of sec with Vol DL < 6250B                  689
Nb of sec with Vol UL < 1250B                  766
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 0
Total DL (Bytes)                                 0
dtype: int64

In [36]:
#calculate the skewness of each column
telco_df_dropped.skew(axis='index', skipna=True)

Bearer Id                                     0.021424
Start ms                                      0.000499
End ms                                       -0.000738
Dur. (ms)                                     3.969863
IMSI                                       -269.208189
MSISDN/Number                               331.498405
IMEI                                          1.068722
Avg RTT DL (ms)                              67.061903
Avg RTT UL (ms)                              28.611111
Avg Bearer TP DL (kbps)                       2.589701
Avg Bearer TP UL (kbps)                       4.496712
TCP DL Retrans. Vol (Bytes)                  15.844908
TCP UL Retrans. Vol (Bytes)                  83.299761
DL TP < 50 Kbps (%)                          -2.302061
50 Kbps < DL TP < 250 Kbps (%)                3.282171
250 Kbps < DL TP < 1 Mbps (%)                 4.575920
DL TP > 1 Mbps (%)                            5.359140
UL TP < 10 Kbps (%)                          -8.997207
10 Kbps < UL TP < 50 Kbps (%)                10.961498
50 Kbps < UL TP < 300 Kbps (%)               21.855024
UL TP > 300 Kbps (%)                         36.076913
HTTP DL (Bytes)                              38.608077
HTTP UL (Bytes)                              32.195308
Activity Duration DL (ms)                     5.849471
Activity Duration UL (ms)                     7.354249
Dur. (ms).1                                   3.969863
Nb of sec with 125000B < Vol DL               6.558617
Nb of sec with 1250B < Vol UL < 6250B        21.896781
Nb of sec with 31250B < Vol DL < 125000B      6.577101
Nb of sec with 37500B < Vol UL               21.452869
Nb of sec with 6250B < Vol DL < 31250B        6.858747
Nb of sec with 6250B < Vol UL < 37500B       19.521070
Nb of sec with Vol DL < 6250B                 9.023094
Nb of sec with Vol UL < 1250B                 7.479992
Social Media DL (Bytes)                      -0.001713
Social Media UL (Bytes)                      -0.000123
Google DL (Bytes)                            -0.008673
Google UL (Bytes)                             0.002430
Email DL (Bytes)                             -0.002563
Email UL (Bytes)                              0.006938
Youtube DL (Bytes)                           -0.000043
Youtube UL (Bytes)                           -0.000856
Netflix DL (Bytes)                           -0.002427
Netflix UL (Bytes)                           -0.000345
Gaming DL (Bytes)                            -0.004012
Gaming UL (Bytes)                            -0.002507
Other DL (Bytes)                              0.000966
Other UL (Bytes)                              0.001494
Total UL (Bytes)                             -0.002034
Total DL (Bytes)                             -0.003682
dtype: float64

In [40]:
telco_df_dropped.fillna(value=0, inplace=True)

In [41]:
telco_df_dropped.isna().sum()

Bearer Id                                   0
Start                                       0
Start ms                                    0
End                                         0
End ms                                      0
Dur. (ms)                                   0
IMSI                                        0
MSISDN/Number                               0
IMEI                                        0
Last Location Name                          0
Avg RTT DL (ms)                             0
Avg RTT UL (ms)                             0
Avg Bearer TP DL (kbps)                     0
Avg Bearer TP UL (kbps)                     0
TCP DL Retrans. Vol (Bytes)                 0
TCP UL Retrans. Vol (Bytes)                 0
DL TP < 50 Kbps (%)                         0
50 Kbps < DL TP < 250 Kbps (%)              0
250 Kbps < DL TP < 1 Mbps (%)               0
DL TP > 1 Mbps (%)                          0
UL TP < 10 Kbps (%)                         0
10 Kbps < UL TP < 50 Kbps (%)               0
50 Kbps < UL TP < 300 Kbps (%)              0
UL TP > 300 Kbps (%)                        0
HTTP DL (Bytes)                             0
HTTP UL (Bytes)                             0
Activity Duration DL (ms)                   0
Activity Duration UL (ms)                   0
Dur. (ms).1                                 0
Handset Manufacturer                        0
Handset Type                                0
Nb of sec with 125000B < Vol DL             0
Nb of sec with 1250B < Vol UL < 6250B       0
Nb of sec with 31250B < Vol DL < 125000B    0
Nb of sec with 37500B < Vol UL              0
Nb of sec with 6250B < Vol DL < 31250B      0
Nb of sec with 6250B < Vol UL < 37500B      0
Nb of sec with Vol DL < 6250B               0
Nb of sec with Vol UL < 1250B               0
Social Media DL (Bytes)                     0
Social Media UL (Bytes)                     0
Google DL (Bytes)                           0
Google UL (Bytes)                           0
Email DL (Bytes)                            0
Email UL (Bytes)                            0
Youtube DL (Bytes)                          0
Youtube UL (Bytes)                          0
Netflix DL (Bytes)                          0
Netflix UL (Bytes)                          0
Gaming DL (Bytes)                           0
Gaming UL (Bytes)                           0
Other DL (Bytes)                            0
Other UL (Bytes)                            0
Total UL (Bytes)                            0
Total DL (Bytes)                            0
dtype: int64

In [43]:
telco_df_dropped.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,42.0,5.0,23.0,44.0,0.0,0.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,0.0,0.0,0.0,0.0,0.0,0.0,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,0.0,0.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),0.0,0.0,0.0,0.0,0.0,0.0,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,0.0,0.0,6.0,9.0,0.0,0.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),0.0,0.0,0.0,0.0,0.0,0.0,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,0.0,0.0,44.0,44.0,0.0,0.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,3330.0,37882.0,1.321510e+09,undefined,undefined,0.0,0.0,0.0,0.0,0.0,0.0,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,0.0,0.0,6.0,9.0,0.0,0.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,0.0,0.0,0.0,0.0,0.0,0.0,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

## Task 1

#### Group the dataset by handset type

In [50]:

toHandset = telco_df_dropped['Handset Type'].value_counts()

In [51]:
toHandset.head(10)

Huawei B528S-23A                19724
Apple iPhone 6S (A1688)          9391
Apple iPhone 6 (A1586)           8991
undefined                        8892
Apple iPhone 7 (A1778)           6274
Apple iPhone Se (A1723)          5165
Apple iPhone 8 (A1905)           4977
Apple iPhone Xr (A2105)          4555
Samsung Galaxy S8 (Sm-G950F)     4459
Apple iPhone X (A1901)           3805
Name: Handset Type, dtype: int64

In [57]:
#### Group the dataset by handset Manufacturers
toHandsetManufacturer = telco_df_dropped['Handset Manufacturer'].value_counts()
toHandsetManufacturer.head(3)

Apple      59304
Samsung    40393
Huawei     34269
Name: Handset Manufacturer, dtype: int64

In [74]:
df = telco_df_dropped.groupby('Handset Type')['Handset Manufacturer'].count()

In [ ]:
!pip list

In [3]:
%run ../scripts/user_overview_analysis.py

SyntaxError: unexpected EOF while parsing (user_overview_analysis.py, line 52)

In [17]:
import sys
sys.path.append('../scripts')
import user_overview_analysis
import copy

In [18]:
df = copy.deepcopy(user_overview_analysis.telco_df)
df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [15]:
df = user_overview_analysis.clean_data(df)
df.head()

C:\Users\User\anaconda3\envs\envMysql\lib\site-packages\pandas\core\series.py:4536: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

AttributeError: 'NoneType' object has no attribute 'head'

In [ ]:
user_overview_analysis.get_top_handsets()

In [4]:
python -m ../scripts/user_boverview_analysis.py

SyntaxError: invalid syntax (<ipython-input-4-ddf986a3227b>, line 1)

In [1]:
import streamlit